### ISSUE TITLE
Import Orders

### ISSUE THREAD

**Issue by LEVDC001** [Acumatica/Acumatica-AmazonIntegration#2]
We have just setup the software and have setup the integration mapping through the Marketplace configuration option as per the recommendation, however when we run the import orders option we get an error message "Error 'branch' cannot be empty". I have reviewed the source object and source field and a branch that I have created in Acumatica will not exist in the import from Amazon. I have tried using hard coding by selecting 'OrderItem' as the source object and putting a formula in the source field like ='ACS' (which is the branch code in Acumatica). This returns error message "Object reference not set to and instance of an object". I an assuming either you cannot use formulas, the syntax is incorrect or there is another method to include the branch. In summary my question is how to add a branch into the mapping table for the Market place configuration option

**Comment by DhirenChhapgar** [comment]
Issue could be due to cash account not setup for payment method being used for customer. 
Also, expression editor is not supported in mapping.
