### ISSUE TITLE
Imported Orders not mapping Shipping Address To Ship To Street Address

### ISSUE THREAD

**Issue by JBeckEntr** [Acumatica/Acumatica-AmazonIntegration#3]
Using your mapping for the integration and the City, State, Postal etc maps great, but it will not pull the Order->ShippingAddress AddressLine1 and map it to the Shipping Settings-> Ship-To Address  Address Line 1 within Acumatica.

**Comment by DhirenChhapgar** [comment]
Our integration imports these values in Acumatica if they are returned via Amazon MWS working with your seller central. 
I believe you are required to complete MWS Security form to get these values. 
This [link](https://sellercentral.amazon.com/forums/t/listorders-missing-data/463393) may be helpful.
